version: "2"

services:
  backend:
    build:
      context: ./backend
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    depends_on:
      - mongodb
    networks:
      - default

  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    volumes:
      - ./data-node:/data/db
    ports:
      - 27017:27017
    command: mongod
    networks:
      - default

networks:
  default:
    driver: bridge
