apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_ID}-deployment
  namespace: ${KUBE_NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${APP_ID}
  template:
    metadata:
      labels:
        app: ${APP_ID}
    spec:
      containers:
      - name: ${APP_ID}
        image: ${DOCKER_USERNAME}/${APP_ID}:${VERSION}
        ports:
        - containerPort: ${API_PORT}
        env:
          - name: JURINET_URL
            value: ${JURINET_URL}
          - name: JURINET_DBNAME
            value: ${JURINET_DBNAME}
          - name: JURICA_URL
            value: ${JURICA_URL}
          - name: JURICA_DBNAME
            value: ${JURICA_DBNAME}
          - name: JUDIFILTRE_DBNAME
            value: ${JUDIFILTRE_DBNAME}
          - name: JUDIFILTRE_URL
            value: ${JUDIFILTRE_URL}
          - name: ROOT_PATH
            value: ${ROOT_PATH}
          - name: BASE_URL
            value: ${BASE_URL}
          - name: API_PORT
            value: "${API_PORT}"
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - curl -s -k --fail --max-time 2 "http://localhost:${API_PORT}/${ROOT_PATH}/health" | egrep -q '${APP_KEYWORD}'
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 2
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - curl -s -k --fail --max-time 2 "http://localhost:${API_PORT}/${ROOT_PATH}/health" | egrep -q '${APP_KEYWORD}'
          initialDelaySeconds: 15
          periodSeconds: 15
          failureThreshold: 10
          timeoutSeconds: 2
        securityContext:
          runAsUser: 1000
          capabilities:
            drop:
              - all
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true