name: 🐋☸️ Build, Publish, Deploy (push master)

on:
  push:
    branches: [master]

jobs:
  build-publish:
    runs-on: ubuntu-latest
    env:
      APP_ID: judifiltre-* # specific to backend or client
      APP_GROUP: judilibre-prive
      APP_HOST: judifiltre.judilibre-prive.local
      APP_PORT: 443
      APP_SCHEME: https
      APP_SELF_SIGNED: "true"
      APP_KEYWORD: specific # to backend or client
      DOCKER_USERNAME: opendatajustice
      KUBECONFIG: /home/runner/.kube/config-local-k3s.yaml
      KUBE_NAMESPACE: judilibre-prive-local-dev
      KUBE_TYPE: k3s
      KUBE_ZONE: local
      ROOT_PATH: judifiltre* # specific to backend or client
      START_TIMEOUT: 240
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF} | sed 's|^refs/heads/||;' | sed 's/[^a-zA-Z0-9]/-/g')"
        id: extract_branch
      - name: Init ops dependencies
        run: ./scripts/init_deps.sh && ./scripts/check_install.sh
        env:
          GIT_BRANCH: ${{ steps.extract_branch.outputs.branch }}
      - name: 🔙  Get version -- backend
        run: echo "##[set-output name=version;]$(./scripts/version.sh)"
        id: backend_version
        env:
          APP_ID: judifiltre-backend
      - name: 🔙🐋 Check if build is needed -- backend
        run: |
          echo "##[set-output name=status;]$(./scripts/docker-check.sh || echo build_needed)"
        id: backend_check
        env:
          GIT_BRANCH: ${{ steps.extract_branch.outputs.branch }}
          VERSION: ${{ steps.backend_version.outputs.version }}
          APP_ID: judifiltre-backend
      - name: 👤  Get version -- client
        run: echo "##[set-output name=version;]$(./scripts/version.sh)"
        id: client_version
        env:
          APP_ID: judifiltre-client
      - name: 👤🐋 Check if build is needed -- client
        run: |
          echo "##[set-output name=status;]$(./scripts/docker-check.sh || echo build_needed)"
        id: client_check
        env:
          GIT_BRANCH: ${{ steps.extract_branch.outputs.branch }}
          VERSION: ${{ steps.client_version.outputs.version }}
          APP_ID: judifiltre-client
      - name: Use Node.js ${{ matrix.node-version }}
        if: (steps.client_check.outputs.status == 'build_needed') || (steps.backend_check.outputs.status == 'build_needed')
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: 🔙 build Node backend
        run: yarn buildBackend --
        if: (steps.backend_check.outputs.status == 'build_needed')
      - name: 🔙🐋 Build docker image -- backend
        if: (matrix.node-version == '16.x') && (steps.backend_check.outputs.status == 'build_needed')
        run: ./scripts/docker-build.sh
        env:
          APP_ID: judifiltre-backend
          DOCKER_TARGET: judifiltre-backend
          VERSION: ${{ steps.backend_version.outputs.version }}
      - name: 🔙☸️ Deploy k8s services locally -- backend
        if: (matrix.node-version == '16.x') && (steps.backend_check.outputs.status == 'build_needed')
        run: ./scripts/deploy_k8s_services.sh
        env:
          APP_ID: judifiltre-backend
          API_PORT: 8080
          APP_KEYWORD: "\"disponible\""
          GIT_BRANCH: ${{ steps.extract_branch.outputs.branch }}
          ROOT_PATH: judifiltre/api
          VERSION: ${{ steps.backend_version.outputs.version }}
      - name: 🔙 initDb for test -- backend
        if: (matrix.node-version == '16.x') && (steps.backend_check.outputs.status == 'build_needed')
        run: kubectl -n ${KUBE_NAMESPACE} exec $(kubectl -n ${KUBE_NAMESPACE} get pods | grep judifiltre-backend | awk '{print $1}')  --  node dist/app/scripts/initDbDev.js
      - name: 🔙✅ Execute minimal tests -- backend
        if: (matrix.node-version == '16.x') && (steps.backend_check.outputs.status == 'build_needed')
        run: |
          echo "127.0.0.1 ${APP_HOST}" | sudo tee -a /etc/hosts
          kubectl get pods --namespace=${KUBE_NAMESPACE}
          kubectl logs service/${APP_ID}-svc --namespace=${KUBE_NAMESPACE}
          ./scripts/test_minimal.sh
        env:
          APP_ID: judifiltre-backend
          APP_KEYWORD: "\"disponible\""
          GIT_BRANCH: ${{ steps.extract_branch.outputs.branch }}
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
          ROOT_PATH: judifiltre/api
      - name: 🔙🚀 Push docker image -- backend
        if: (matrix.node-version == '16.x') && (steps.backend_check.outputs.status == 'build_needed') && (github.event_name == 'push')
        run: |
          echo "${DOCKER_TOKEN}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
          DOCKER_IMAGE=${DOCKER_USERNAME}/${APP_ID}:${VERSION}
          docker push ${DOCKER_IMAGE};
          docker tag ${DOCKER_IMAGE} ${DOCKER_USERNAME}/${APP_ID}:$(echo ${VERSION} | sed 's/-.*//')
          docker push ${DOCKER_USERNAME}/${APP_ID}:$(echo ${VERSION} | sed 's/-.*//')
          docker tag ${DOCKER_IMAGE} ${DOCKER_USERNAME}/${APP_ID}:latest
          docker push ${DOCKER_USERNAME}/${APP_ID}:latest
        env:
          APP_ID: judifiltre-backend
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          VERSION: ${{ steps.backend_version.outputs.version }}
      - name: 👤  Build static app -- client
        if: (matrix.node-version == '16.x') && (steps.client_check.outputs.status == 'build_needed')
        run: |
          export VERSION=$(./scripts/version.sh)
          export DOCKER_IMAGE=${DOCKER_USERNAME}/${APP_ID}:${VERSION}
          if ! (docker manifest inspect ${DOCKER_IMAGE}); then
            yarn buildClient || echo "ugly worakound";
          fi
        env:
          APP_ID: judifiltre-client
          REACT_APP_API_URL: /judifiltre/api/
      - name: 👤🐋 Build docker image -- client
        if: (matrix.node-version == '16.x') && (steps.client_check.outputs.status == 'build_needed')
        run: ./scripts/docker-build.sh
        env:
          APP_ID: judifiltre-client
          DOCKER_TARGET: judifiltre-client
          VERSION: ${{ steps.client_version.outputs.version }}
      - name: 👤☸️ Deploy k8s services locally -- client
        if: (matrix.node-version == '16.x') && (steps.client_check.outputs.status == 'build_needed')
        run: ./scripts/deploy_k8s_services.sh
        env:
          APP_ID: judifiltre-client
          API_PORT: 3000
          GIT_BRANCH: ${{ steps.extract_branch.outputs.branch }}
          ROOT_PATH: judifiltre
          VERSION: ${{ steps.client_version.outputs.version }}
      - name: 👤✅ Execute minimal tests -- client
        if: (matrix.node-version == '16.x') && (steps.client_check.outputs.status == 'build_needed')
        run: |
          echo "127.0.0.1 ${APP_HOST}" | sudo tee -a /etc/hosts
          kubectl get pods --namespace=${KUBE_NAMESPACE}
          kubectl logs service/${APP_ID}-svc --namespace=${KUBE_NAMESPACE}
          ./scripts/test_minimal.sh
        env:
          APP_ID: judifiltre-client
          APP_KEYWORD: html
          GIT_BRANCH: ${{ steps.extract_branch.outputs.branch }}
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
          ROOT_PATH: judifiltre
      - name: 👤🚀 Push docker image -- client
        if: (matrix.node-version == '16.x') && (steps.client_check.outputs.status == 'build_needed') && (github.event_name == 'push')
        run: |
          echo "${DOCKER_TOKEN}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
          DOCKER_IMAGE=${DOCKER_USERNAME}/${APP_ID}:${VERSION}
          docker push ${DOCKER_IMAGE};
          docker tag ${DOCKER_IMAGE} ${DOCKER_USERNAME}/${APP_ID}:$(echo ${VERSION} | sed 's/-.*//')
          docker push ${DOCKER_USERNAME}/${APP_ID}:$(echo ${VERSION} | sed 's/-.*//')
          docker tag ${DOCKER_IMAGE} ${DOCKER_USERNAME}/${APP_ID}:latest
          docker push ${DOCKER_USERNAME}/${APP_ID}:latest
        env:
          APP_ID: judifiltre-client
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          VERSION: ${{ steps.client_version.outputs.version }}
  deploy:
    needs: build-publish
    runs-on: [self-hosted]
    env:
      APP_ID: judifiltre-* # specific to backend or client
      APP_GROUP: judilibre-prive
      APP_HOST: judifiltre.judilibre-prive.local
      APP_PORT: 443
      APP_SCHEME: https
      APP_SELF_SIGNED: "true"
      APP_KEYWORD: specific # to backend or client
      DOCKER_USERNAME: opendatajustice
      KUBE_NAMESPACE: judilibre-prive-judifiltre
      KUBE_SERVICES_FORCE_UPDATE: deployment #temporary force re-deployment if config changed
      KUBE_TYPE: k3s
      KUBE_ZONE: prive
      ROOT_PATH: judifiltre* # specific to backend or client
      START_TIMEOUT: 240
    steps:
      - uses: actions/checkout@v2
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF} | sed 's|^refs/heads/||;' | sed 's/[^a-zA-Z0-9]/-/g')"
        id: extract_branch
      - name: Init ops dependencies
        run: ./scripts/init_deps.sh && ./scripts/check_install.sh
        env:
          GIT_BRANCH: ${{ steps.extract_branch.outputs.branch }}
      - name: 🔙  Get version -- backend
        run: echo "##[set-output name=version;]$(./scripts/version.sh)"
        id: backend_version
        env:
          APP_ID: judifiltre-backend
      - name: 👤  Get version -- client
        run: echo "##[set-output name=version;]$(./scripts/version.sh)"
        id: client_version
        env:
          APP_ID: judifiltre-client
      - name: 🔙☸️ Deploy k8s services -- backend
        run: ./scripts/deploy_k8s_services.sh || (echo K8S LOGS && cat $(ls -tr k8s*log | tail -1) && exit 1)
        env:
          APP_ID: judifiltre-backend
          API_PORT: 8080
          APP_KEYWORD: "\"disponible\""
          GIT_BRANCH: ${{ steps.extract_branch.outputs.branch }}
          # MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
          JURICA_URL: ${{ secrets.JURICA_URL }}
          JURICA_DBNAME: ${{ secrets.JURICA_DBNAME }}
          JURINET_URL: ${{ secrets.JURINET_URL }}
          JURINET_DBNAME: ${{ secrets.JURINET_DBNAME }}
          JUDIFILTRE_URL: ${{ secrets.JUDIFILTRE_URL }}
          JUDIFILTRE_DBNAME: ${{ secrets.JUDIFILTRE_DBNAME }}
          ROOT_PATH: judifiltre/api
          VERSION: ${{ steps.backend_version.outputs.version }}
      - name: 🔙 initDb for test -- backend
        run: kubectl -n ${KUBE_NAMESPACE} exec $(kubectl -n ${KUBE_NAMESPACE} get pods | grep judifiltre-backend | awk '{print $1}')  --  node dist/app/scripts/initDb.js
      - name: 🔙🚀 Update remote app ☸️ -- backend
        run: |
          ./scripts/update_app.sh || (echo K8S LOGS && cat $(ls -tr k8s*log | tail -1) && exit 1)
          kubectl get pods --namespace=${KUBE_NAMESPACE}
          kubectl logs service/${APP_ID}-svc --namespace=${KUBE_NAMESPACE}
        env:
          APP_ID: judifiltre-backend
          APP_KEYWORD: "\"disponible\""
          GIT_BRANCH: ${{ steps.extract_branch.outputs.branch }}
          ROOT_PATH: judifiltre/api
          START_TIMEOUT: 20
          VERSION: ${{ steps.backend_version.outputs.version }}
      - name: 🔙🧹 Clean old replicas ☸️ -- backend
        run: ./scripts/clean_old_replicas.sh
        env:
          APP_ID: judifiltre-backend
          GIT_BRANCH: ${{ steps.extract_branch.outputs.branch }}
          VERSION: ${{ steps.backend_version.outputs.version }}
      - name: 👤☸️ Deploy k8s services -- client
        run: ./scripts/deploy_k8s_services.sh || (echo K8S LOGS && cat $(ls -tr k8s*log | tail -1) && exit 1)
        env:
          APP_ID: judifiltre-client
          API_PORT: 3000
          GIT_BRANCH: ${{ steps.extract_branch.outputs.branch }}
          ROOT_PATH: judifiltre
          VERSION: ${{ steps.client_version.outputs.version }}
      - name: 👤🚀 Update remote app ☸️ -- client
        run: |
          ./scripts/update_app.sh || (echo K8S LOGS && cat $(ls -tr k8s*log | tail -1) && exit 1)
          kubectl get pods --namespace=${KUBE_NAMESPACE}
          kubectl logs service/${APP_ID}-svc --namespace=${KUBE_NAMESPACE}
        env:
          APP_ID: judifiltre-client
          APP_KEYWORD: html
          GIT_BRANCH: ${{ steps.extract_branch.outputs.branch }}
          ROOT_PATH: judifiltre
          START_TIMEOUT: 20
          VERSION: ${{ steps.client_version.outputs.version }}
      - name: 👤🧹 Clean old replicas ☸️ -- client
        run: ./scripts/clean_old_replicas.sh
        env:
          APP_ID: judifiltre-client
          GIT_BRANCH: ${{ steps.extract_branch.outputs.branch }}
          VERSION: ${{ steps.client_version.outputs.version }}
